In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"D:\Admin\Downloads\shopping_dataset.csv\shirts.csv")

In [5]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SPY███ LI███TYL█████████E L█████████,"[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...",NaN,19t███loo███F W█████████s C███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,20308620,Arrow,Men Blue Original Slim Fit Grid Tattersall Che...,4.0,59,2499.0,50.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":11,""4_stars""...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""38"",""value"":""41.73in"",""value_name"":""...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
93,18960194,The Indian Garage Co,Men White Printed Casual Cotton Shirt,3.9,73,1749.0,72.0,"""₹349.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":11,""4_stars""...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
94,19276504,Turtle,Men Beige Printed Cotton Slim Fit Casual Shirt,4.7,7,1399.0,40.0,"""₹839.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Tur███ Li███ed,"[{""size"":""39"",""value"":""43.0in"",""value_name"":""C...",NaN,Lem███Fre███ Bl█████████d F███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
95,19299798,Louis Philippe,Men Navy Blue Solid Slim Fit Formal Shirt,4.4,32,2799.0,NaN,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ret███Net███,"[{""size"":""39"",""value"":""44.15in"",""value_name"":""...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
96,18903374,Levis,Women Blue Pure Cotton Casual Shirt,4.6,168,2599.0,45.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":8,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""XS"",""value"":""35.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

In [7]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SPY███ LI███TYL█████████E L█████████,"[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...",NaN,19t███loo███F W█████████s C███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
92,20308620,Arrow,Men Blue Original Slim Fit Grid Tattersall Che...,4.0,59,2499.0,50.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":11,""4_stars""...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""38"",""value"":""41.73in"",""value_name"":""...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
93,18960194,The Indian Garage Co,Men White Printed Casual Cotton Shirt,3.9,73,1749.0,72.0,"""₹349.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":11,""4_stars""...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
94,19276504,Turtle,Men Beige Printed Cotton Slim Fit Casual Shirt,4.7,7,1399.0,40.0,"""₹839.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Tur███ Li███ed,"[{""size"":""39"",""value"":""43.0in"",""value_name"":""C...",NaN,Lem███Fre███ Bl█████████d F███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
95,19299798,Louis Philippe,Men Navy Blue Solid Slim Fit Formal Shirt,4.4,32,2799.0,NaN,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ret███Net███,"[{""size"":""39"",""value"":""44.15in"",""value_name"":""...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
96,18903374,Levis,Women Blue Pure Cotton Casual Shirt,4.6,168,2599.0,45.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":8,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""XS"",""value"":""35.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

In [11]:
df.shape

(97, 24)

In [13]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [19]:
numeric_cols = df.select_dtypes(include = ['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(0)

In [21]:
object_cols = df.select_dtypes(include = ['object']).columns
df[object_cols] = df[object_cols].fillna("Unknown")

In [23]:
df = df.drop_duplicates()

In [25]:
df[['title', 'final_price', 'rating']]

                   title  final_price  rating
0                 SPYKAR  "₹1,499.00"     2.9
1   The Indian Garage Co    "₹507.00"     4.2
2   The Indian Garage Co    "₹454.00"     4.4
3   The Indian Garage Co    "₹454.00"     4.0
4        U.S. Polo Assn.  "₹1,559.00"     4.2
..                   ...          ...     ...
92                 Arrow  "₹2,499.00"     4.0
93  The Indian Garage Co    "₹349.00"     3.9
94                Turtle    "₹839.00"     4.7
95        Louis Philippe  "₹2,519.00"     4.4
96                 Levis  "₹2,079.00"     4.6

[97 rows x 3 columns]

In [27]:
df[df['rating'] > 4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",Unknown,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",Unknown,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
5,18996772,U.S. Polo Assn.,U S Polo Assn Men Coral and Blue Striped 100% ...,4.9,10,2799.0,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Tight""}...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",Unknown,10T███LOO███DU █████████ITY███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
7,18960086,The Indian Garage Co,Men Green Slim Fit Horizontal Stripes Casual S...,4.5,23,1749.0,72.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████Y -██████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",Unknown,"No.███1, ███ur █████████lur█████████████████████8","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
12,18463946,Lee,Men Pink Slim Fit Tartan Checks Checked Casual...,4.5,15,2399.0,50.0,"""₹2,399.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""39"",""value"":""38.19in"",""value_name"":""...",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
13,13621622,U.S. Polo Assn.,Men Blue Regular Fit Printed Casual Shirt,4.4,41,2399.0,0.0,"""₹2,399.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":6,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...","[""rw-13621622_cae700"",""https://videos.myntasse...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
15,17719808,Louis Philippe Jeans,Men Green & White Slim Fit Tartan Checked Pure...,4.5,18,2199.0,31.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Unknown,"[{""size"":""38"",""value"":""42.15in"",""value_name"":""...",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
16,18759238,HERE&NOW,Women Yellow And Black Polka Dot Printed Casua...,4.3,32,1399.0,47.0,"""₹741.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":3,""4_stars"":...",Unknown,Omn███ch ███ail███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"11t███loo███Fla█████████6, ███████████████████...",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
17,20394602,Cantabil,Men Black Solid Cotton Formal Shirt,4.4,38,1999.0,60.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""38"",""value"":""40.5in"",""value_name"":""C...",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
18,13672974,WROGN,Men White & Red Regular Fit Checked Casual Shirt,4.1,250,2599.0,55.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":21,""2_stars"":12,""3_stars"":23,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""39"",""value"":""42.25in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
19,13694492,Ecentric,Men Cream-Coloured Slim Fit Eco-Friendly Hemp ...,4.5,22,2499.0,35.0,"""₹1,624.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Ece███ic ███ia █████████,"[{""size"":""38"",""value"":""40.0in"",""value_name"":""C...",Unknown,142███ 5t███ros█████████ipp███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",shirts
20,21388884,French Connection,Slim Fit Striped Cotton Casual Shirt,4.3,58,2199.0,70.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/213...,...,"{""1_star"":0,""2_stars"":6,""3_stars"":5,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""38"",""value"":""40.25in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
22,21396820,Jack & Jones,Men Slim Fit Printed Casual Shirt,4.4,15,3499.0,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/213...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""38"",""value"":""39.2in"",""value_name"":""C...",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
23,16042682,Nautica,Men Navy Blue Printed Casual Shirt,4.2,15,3599.0,50.0,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SAN███ETA███ PV██████,"[{""size"":""38"",""value"":""40.5in"",""value_name"":""C...",Unknown,Sho███o. ███-10█████████enu███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
25,18996754,U.S. Polo Assn.,U S Polo Assn Men Brown Tartan Checks Checked ...,4.1,9,2599.0,50.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",Unknown,10T███LOO███DU █████████ITY███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
27,17296250,CAVIO,Boys Green & Black Colourblocked Casual Shirt,4.3,20,1290.0,33.0,"""₹864.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",Unknown,Pun███ Ap███els█████████,"[{""size"":""2-3Y"",""value"":""25.0in"",""value_name"":...",Unknown,"145███7,R███YMA█████████XPA███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
29,17280264,HIGHLANDER,Men Sea Green & Pink Slim Fit Printed Cotton C...,4.2,1246,1199.0,59.0,"""₹491.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":87,""2_stars"":35,""3_stars"":118,""4_sta...","[{""percentage"":""74"",""value_name"":""Fit, Just Ri...",Fla███tar███mme██████,"[{""size"":""39"",""value"":""41.0in"",""value_name"":""C...",Unknown,"1st███oor███abi█████████02,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
35,17307612,Louis Philippe Jeans,Men Blue Slim Fit Checked Casual Cotton Shirt,4.3,23,2199.0,30.0,"""₹1,539.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,Ret███Net███,"[{""size"":""39"",""value"":""44.15in"",""value_name"":""...",Unknown,Blo███B-1███abi█████████-24███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
36,17345842,JC Collection,Women Blue Abstract Printed Casual Shirt,4.1,12,3499.0,45.0,"""₹1,924.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Sup███om ███,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""Bu...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
43,17307656,SIMON CARTER LONDON,Men White Slim Fit Floral Printed Casual Shirt,4.6,5,2799.0,60.0,"""₹1,119.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""39"",""value"":""42.3in"",""value_name"":""C...",Unknown,"Gro███ Fl███, N█████████old███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
44,17313630,JAINISH,Men Blue Classic Formal Shirt,4.1,68,1999.0,71.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":5,""2_stars"":4,""3_stars"":8,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",IND███ NE███E P█████████MIT███,"[{""size"":""36"",""value"":""39.0in"",""value_name"":""C...",Unknown,"HOU███NO.███ GR█████████R, ███████████████████...","[{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
45,17342230,Pepe Jeans,Boys White Printed Casual Shirt,4.3,6,1599.0,55.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Vis███ St███,"[{""size"":""3-5Y"",""value"":""27.55in"",""value_name""...",Unknown,3rd███oor███o. █████████Mai███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
46,17331296,Fabindia,Men Blue Stripes Striped Cotton Casual Shirt,4.4,5,1699.0,0.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,FAB███IA ███ITE███,"[{""size"":""39"",""value"":""36.0in"",""value_name"":""C...",Unknown,FAB███IA ███ITE█████████ly ███████████████████...,Unknown,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
48,17355884,Mast & Harbour,Men Green & Navy Blue Checked Pure Cotton Casu...,4.1,167,1999.0,65.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":13,""2_stars"":3,""3_stars"":19,""4_stars...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",PRE███R A███REL███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",Unknown,"NO ███3, ███EME█████████D, ███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
50,17293106,DressBerry,Women Pink & White Slim Fit Floral Printed Cas...,4.2,622,1599.0,59.0,"""₹591.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":50,""2_stars"":26,""3_stars"":40,""4_star...",Unknown,Pat███a H███e,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,B/4███ Ra███ Ra█████████le ███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
51,17342236,Pepe Jeans,Boys Yellow & Blue Cotton Checked Casual Shirt,4.4,16,1599.0,55.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,Vis███ St███,"[{""size"":""3-5Y"",""value"":""27.55in"",""value_name""...",Unknown,3rd███oor███o. █████████Mai███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
53,17375000,ColorPlus,Men Red Printed Casual Shirt,4.5,15,2399.0,30.0,"""₹1,151.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ray███d L███ted███,"[{""size"":""38"",""value"":""43.0in"",""value_name"":""C...",Unknown,"RAY███D L███TED█████████, P███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
56,17289100,Roadster,The Life Co. Spread Collar Pure Cotton Casual...,4.3,7,1899.0,55.0,"""₹854.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,STR███LIN███PPA█████████ATE█████████,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...",Unknown,"B-0███cto███5, █████████uta███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
58,17302022,Pantaloons Junior,Boys Blue Solid Cotton Casual Shirt,4.4,77,799.0,14.0,"""₹687.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":4,""4_stars"":...",Unknown,Wes███ry ███din█████████d_P████████████,"[{""size"":""8-9Y"",""value"":""32.0in"",""value_name"":...",Unknown,Wes███ry ███din█████████e L███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
63,18970712,Tommy Hilfiger,Boys Corduroy Casual Shirt,4.5,10,3299.0,40.0,"""₹1,979.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""5-6Y"",""value"":""26.68in"",""value_name""...",Unknown,PVH███vin███ash█████████tdN███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
64,18960126,The Indian Garage Co,Men Peach-Coloured Printed Casual Cotton Shirt,4.1,21,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",Unknown,1 s███loo███Cab█████████-01███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
66,18970848,Tommy Hilfiger,Boys Green & Blue Tartan Checks Pure Cotton Ca...,4.6,14,2799.0,40.0,"""₹1,679.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""4-5Y"",""value"":""25.89in"",""value_name""...",Unknown,PVH███vin███ash█████████tdN███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
67,18969276,Ruhaans,Women Black Classic Casual Shirt,4.1,14,1399.0,54.0,"""₹643.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,SHI███BOA███RAD█████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",Unknown,FIR███FLO███ RZ█████████OCK███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
71,13692652,M&H Our Water,Men Rust Brown & Off-White Slim Fit Checked Su...,4.2,78,2499.0,0.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":4,""2_stars"":2,""3_stars"":8,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""38"",""value"":""40.88in"",""value_name"":""...","[""rw-13692652_cae700""]",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
72,13768790,Nautica,Men Blue & White Slim Fit Printed Smart Casual...,4.3,40,3299.0,50.0,"""₹3,299.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""39"",""value"":""41.5in"",""value_name"":""C...",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
73,13453254,DENNISON,Men Mauve Smart Slim Fit Solid Cotton Linen Ca...,4.6,7,2199.0,74.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Tight""}...",Unknown,"[{""size"":""38"",""value"":""40.0in"",""value_name"":""C...",Unknown,Unknown,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
74,18450788,Nautica,Men Teal Blue And White Slim Fit Micro Checked...,4.3,118,4299.0,0.0,"""₹4,299.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":11,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""38"",""value"":""42.0in"",""value_name"":""C...","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
75,18690268,Dennis Lingo,Men Slim Fit Tropical Casual Shirt,4.6,5,1999.0,80.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,Unknown,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",Unknown,Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts

In [29]:
df['quantity'] = 1

In [31]:
df['total_amount'] = df['final_price'] * df['quantity']

In [35]:
df[['title', 'final_price', 'quantity', 'total_amount']].head()

                  title  final_price  quantity total_amount
0                SPYKAR  "₹1,499.00"         1  "₹1,499.00"
1  The Indian Garage Co    "₹507.00"         1    "₹507.00"
2  The Indian Garage Co    "₹454.00"         1    "₹454.00"
3  The Indian Garage Co    "₹454.00"         1    "₹454.00"
4       U.S. Polo Assn.  "₹1,559.00"         1  "₹1,559.00"

In [37]:
df.to_csv("cleaned_shirts_dataset_csv", index = False)

In [43]:
import os
os.getcwd()

'C:\\Users\\Admin'

In [45]:
import os
print(os.path.abspath("cleaned_shirts_dataset_csv"))

C:\Users\Admin\cleaned_shirts_dataset_csv

1. Loaded dataset using Pandas
2. Explored dataset using head(), tail(), shape, columns
3. Handled missing values
4. Removed duplicate rows
5. Filtered rows and selected columns
6. Created total_amount column
7. Saved cleaned dataset as CSV